import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const exportToPDF = async (elementId: string, filename: string = '12kebaad-career-report.pdf') => {
  const element = document.getElementById(elementId);
  if (!element) return;

  // Show loading indicator or handle state outside if needed
  try {
    // 1. Prepare the element for capture
    // Ensure it's temporarily visible and has a white background
    const originalStyle = element.style.cssText;
    element.style.position = 'absolute';
    element.style.left = '0';
    element.style.top = '0';
    element.style.opacity = '1';
    element.style.visibility = 'visible';
    element.style.zIndex = '9999';
    element.style.background = '#ffffff';
    element.style.width = '800px'; // Fixed width for consistent PDF scale

    // 2. Capture using html2canvas
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
      windowWidth: 800
    });

    // 3. Reset element styles
    element.style.cssText = originalStyle;

    // 4. Generate PDF
    const imgData = canvas.toDataURL('image/jpeg', 0.95);
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    const imgWidth = 190; // Reduced from 210 to allow left/right margins (10mm each side)
    const pageHeight = 297; 
    const pageWidth = 210;
    const marginY = 15; // Top and bottom margin in mm
    const marginX = 10; // Left and right margin in mm
    
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = marginY;

    // Add first page
    pdf.addImage(imgData, 'JPEG', marginX, position, imgWidth, imgHeight);
    
    // Add simple footer to first page
    pdf.setFontSize(8);
    pdf.setTextColor(150);
    pdf.text('Page 1 of report - Generated by 12kebaad.in', pageWidth / 2, pageHeight - 10, { align: 'center' });

    heightLeft -= (pageHeight - 2 * marginY);

    let pageNum = 2;
    while (heightLeft >= 0) {
      position = heightLeft - imgHeight + marginY;
      pdf.addPage();
      pdf.addImage(imgData, 'JPEG', marginX, position, imgWidth, imgHeight);
      
      // Footer for subsequent pages
      pdf.text(`Page ${pageNum} of report - Generated by 12kebaad.in`, pageWidth / 2, pageHeight - 10, { align: 'center' });
      
      heightLeft -= (pageHeight - 2 * marginY);
      pageNum++;
    }

    pdf.save(filename);
  } catch (error) {
    console.error('PDF Export Error:', error);
    alert("There was an error generating your PDF. Please try again or use the Print option.");
  }
};
